-- available instances and all data associated with them
LFT_Instances = {
	["rfc"] = {
		name = LFT_DUNGEON_RFC,
		minLevel = 13,
		maxLevel = 19,
		background = "ragefirechasm",
	},
	["fmh"] = {
		name = LFT_DUNGEON_FMH,
		minLevel = 13,
		maxLevel = 20,
		background = "frostmane",
	},
	["wc"] = {
		name = LFT_DUNGEON_WC,
		minLevel = 16,
		maxLevel = 25,
		background = "wailingcaverns",
	},
	["dm"] = {
		name = LFT_DUNGEON_DM,
		minLevel = 16,
		maxLevel = 24,
		background = "deadmines",
	},
	["sfk"] = {
		name = LFT_DUNGEON_SFK,
		minLevel = 20,
		maxLevel = 28,
		background = "shadowfangkeep",
	},
	["stocks"] = {
		name = LFT_DUNGEON_STOCKS,
		minLevel = 23,
		maxLevel = 32,
		background = "stormwindstockades",
	},
	["bfd"] = {
		name = LFT_DUNGEON_BFD,
		minLevel = 22,
		maxLevel = 31,
		background = "blackfathomdeeps",
	},
    ["windhorn"] = {
        name = LFT_DUNGEON_WINDHORN,
        minLevel = 25,
        maxLevel = 33,
        background = "windhorn",
    },
	["smgy"] = {
		name = LFT_DUNGEON_SM_GY,
		minLevel = 30,
		maxLevel = 37,
		background = "scarletmonastery",
	},
	["smlib"] = {
		name = LFT_DUNGEON_SMLIB,
		minLevel = 32,
		maxLevel = 40,
		background = "scarletmonastery",
	},
	["gnomer"] = {
		name = LFT_DUNGEON_GNOMER,
		minLevel = 28,
		maxLevel = 37,
		background = "gnomeregan",
	},
	["rfk"] = {
		name = LFT_DUNGEON_RFK,
		minLevel = 29,
		maxLevel = 36,
		background = "razorfenkraul",
	},
	["tcg"] = {
		name = LFT_DUNGEON_TCG,
		minLevel = 33,
		maxLevel = 39,
		background = "tcg",
	},
	["smarmory"] = {
		name = LFT_DUNGEON_SMARM,
		minLevel = 34,
		maxLevel = 42,
		background = "scarletmonastery",
	},
	["smcath"] = {
		name = LFT_DUNGEON_SMCATH,
		minLevel = 35,
		maxLevel = 45,
		background = "scarletmonastery",
	},
	["rfd"] = {
		name = LFT_DUNGEON_RFD,
		minLevel = 35,
		maxLevel = 44,
		background = "razorfendowns",
	},
	["ulda"] = {
		name = LFT_DUNGEON_ULDA,
		minLevel = 41,
		maxLevel = 50,
		background = "uldaman",
	},
	["gilneas"] = {
		name = LFT_DUNGEON_GILNEAS,
		minLevel = 43,
		maxLevel = 52,
		background = "gilneas",
	},
	["zf"] = {
		name = LFT_DUNGEON_ZF,
		minLevel = 42,
		maxLevel = 51,
		background = "zulfarak",
	},
	["maraorange"] = {
		name = LFT_DUNGEON_MARAORANGE,
		minLevel = 43,
		maxLevel = 51,
		background = "maraudon",
	},
	["marapurple"] = {
		name = LFT_DUNGEON_MARAPURPLE,
		minLevel = 45,
		maxLevel = 52,
		background = "maraudon",
	},
	["maraprincess"] = {
		name = LFT_DUNGEON_MARAPRINCESS,
		minLevel = 46,
		maxLevel = 54,
		background = "maraudon",
	},
	["st"] = {
		name = LFT_DUNGEON_ST,
		minLevel = 49,
		maxLevel = 58,
		background = "sunkentemple",
	},
	["hfq"] = {
		name = LFT_DUNGEON_HFQ,
		minLevel = 51,
		maxLevel = 60,
		background = "hfq",
	},
	["brd"] = {
		name = LFT_DUNGEON_BRD,
		minLevel = 54,
		maxLevel = 60,
		background = "blackrockdepths",
	},
	["brdarena"] = {
		name = LFT_DUNGEON_BRDARENA,
		minLevel = 50,
		maxLevel = 60,
		background = "blackrockdepths",
	},
	["brdemp"] = {
		name = LFT_DUNGEON_BRDEMP,
		minLevel = 54,
		maxLevel = 60,
		background = "blackrockdepths",
	},
	["lbrs"] = {
		name = LFT_DUNGEON_LBRS,
		minLevel = 55,
		maxLevel = 60,
		background = "blackrockspire",
	},
	["dme"] = {
		name = LFT_DUNGEON_DME,
		minLevel = 55,
		maxLevel = 60,
		background = "diremaul",
	},
	["dmn"] = {
		name = LFT_DUNGEON_DMN,
		minLevel = 57,
		maxLevel = 60,
		background = "diremaul",
	},
	["dmt"] = {
		name = LFT_DUNGEON_DMT,
		minLevel = 57,
		maxLevel = 60,
		background = "diremaul",
	},
	["dmw"] = {
		name = LFT_DUNGEON_DMW,
		minLevel = 57,
		maxLevel = 60,
		background = "diremaul",
	},
	["scholo"] = {
		name = LFT_DUNGEON_SCHOLO,
		minLevel = 58,
		maxLevel = 60,
		background = "scholomance",
	},
	["stratud"] = {
		name = LFT_DUNGEON_STRATUD,
		minLevel = 58,
		maxLevel = 60,
		background = "stratholme",
	},
	["stratlive"] = {
		name = LFT_DUNGEON_STRATLIVE,
		minLevel = 58,
		maxLevel = 60,
		background = "stratholme",
	},
	["kc"] = {
		name = LFT_DUNGEON_KC,
		minLevel = 60,
		maxLevel = 60,
		background = "kc",
	},
	["cotbm"] = {
		name = LFT_DUNGEON_COTBM,
		minLevel = 60,
		maxLevel = 60,
		background = "cotbm",
	},
	["swv"] = {
		name = LFT_DUNGEON_SWV,
		minLevel = 60,
		maxLevel = 60,
		background = "swv",
	},
	["swc"] = {
		name = LFT_DUNGEON_SWC,
		minLevel = 32,
		maxLevel = 40,
		background = "swk",
	},
	["swd"] = {
		name = LFT_DUNGEON_SWD,
		minLevel = 35,
		maxLevel = 44,
		background = "swk",
	},
	["dmr"] = {
		name = LFT_DUNGEON_DMR,
		minLevel = 26,
		maxLevel = 35,
		background = "dmr",
	},
}

-- classes and roles they can fill
-- [1] - Tank
-- [2] - Healer
-- [3] - Damage
LFT_ClassRoles = {
	["DRUID"] = { true, true, true },
	["HUNTER"] = { false, false, true },
	["MAGE"] = { false, false, true },
	["PALADIN"] = { true, true, true },
	["PRIEST"] = { false, true, true },
	["ROGUE"] = { false, false, true },
	["SHAMAN"] = { true, true, true },
	["WARLOCK"] = { false, false, true },
	["WARRIOR"] = { true, false, true },
}
